### ISSUE TITLE
PDF gets corrupted when i add logo

### ISSUE THREAD

**Issue by Yoofi-A-Appiah** [Matteljay/invoice-pdfkit#1]
Hello, great package you have here. However, my pdf keeps getting damaged anytime I add the logo to an invoice. I initially thought it was a problem with the file type or size but I have tried all options. Any help with this?
![image](https://github.com/Matteljay/invoice-pdfkit/assets/61325220/f9c0834c-7f45-4213-a38b-6aaa6039c828)

**Comment by Matteljay** [comment]
Hey according to pdfkit, both .jpg and .png should be supported indeed: https://pdfkit.org/docs/images.html
In your screenshot I can only see the typo `log.png` instead of `logo.png`, could that be the cause?
If that still doesn't work, try converting your png to jpg.

**Comment by Yoofi-A-Appiah** [comment]
Hello, I converted the png to jpg and it works now. Thank you
